version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: qso-manager-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: QsoManager
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    command: mongod --auth --bind_ip_all
    networks:
      - qso-network

  qso-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: qso-manager-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__MongoDB=mongodb://admin:password123@mongodb:27017/QsoManager?authSource=admin
    ports:
      - "5041:8080"
    depends_on:
      - mongodb
    networks:
      - qso-network

  qso-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: qso-manager-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - qso-api
    networks:
      - qso-network

networks:
  qso-network:
    driver: bridge
